/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PngEnc */

#ifndef _Included_PngEnc
#define _Included_PngEnc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PngEnc
 * Method:    writePngFile
 * Signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;IIIII)I
 */
JNIEXPORT jint JNICALL Java_PngEnc_writePngFile
  (JNIEnv *, jclass, jstring, jobject, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
